### PR TITLE
Adds project Modern VICE PDB monitor to the projects list

### PR DESCRIPTION
**Pull request by MihaMarkic**
Adds my [pet project](https://github.com/MihaMarkic/modern-vice-pdb-monitor) to the projects list

### CODE REVIEW

**Comment by OmidID** [comment]
@MihaMarkic Cool project. I see you change the Content section too. Please revert that changes and add only your project.
Thanks

**Comment by MihaMarkic** [comment]
> 
> 
> @MihaMarkic Cool project. I see you change the Content section too. Please revert that changes and add only your project.
> Thanks

Oh, autoformatting at work (I merely added my project). Will close and create a new PR.

**Comment by MihaMarkic** [comment]
Here is a [new PR](https://github.com/AvaloniaCommunity/awesome-avalonia/pull/41)

**Comment by FoggyFinder** [comment]
> Oh, autoformatting at work (I merely added my project). Will close and create a new PR.

Nope, you've also added a reference to http://makeapullrequest.com

**Comment by MihaMarkic** [comment]
@FoggyFinder Probably it existed in main branch where I forked from? Otherwise no idea how it got there. Certainly not intentionally.

**Comment by FoggyFinder** [comment]
right, it exists. Really odd then :-)

**Pull request closed without merging**
