### PR TITLE
Add Parquet Floor opensource app

### PR DESCRIPTION
**Pull request by aloneguid**

### CODE REVIEW

**Comment by OmidID** [comment]
Hello @aloneguid 

Maybe is better to refrence to the git source: `https://github.com/aloneguid/parquet-dotnet` and i think it better to put full name `Parquet Floor`.

Thanks

**Comment by aloneguid** [comment]
@OmidID thanks, done!

**Comment by OmidID** [comment]
Thanks for changes @aloneguid 
Very sorry. another comment :)

Now start with `P` and please move it above PixelViewer.

Thanks a lot.

**Comment by aloneguid** [comment]
@OmidID thank you! moved above "Pororoca" as it's mostly a software dev tool. Hope you are ok with that :)

**Pull request merged**
