### PR TITLE
Added PupNet Deploy to Tooling

### PR DESCRIPTION
**Pull request by kuiperzone**

### CODE REVIEW

**Comment by OmidID** [comment]
Hello @kuiperzone 
Thanks for your contribution. I am not sure, But this is not an Avalonia project!

**Comment by OmidID** [comment]
I understand and I am confused about what to do :D 
It may not be a bad idea to create a new section for none avalonia.
What do you think @danwalmsley?

**Comment by kuiperzone** [comment]
Was thinking about it the other day -- it is after all under "tooling" -- i.e. tools for Avalonia. Such tools do not necessarily have to be written with Avalonia, do they?

Is it not under the correct category?

**Comment by Mrxx99** [comment]
I think it makes sense to include as it helps publishing Avalonia apps

Also it has more to do with Avalonia as some other listed libraries like Reactive.History

**Comment by OmidID** [comment]
Looks fine for me too. Do you all suggest in add it in same category or separate one?

**Comment by Mrxx99** [comment]
Tooling looks fine for me. If there are more similar  projects relating to deploying/bundling then it could still be moved to a new category

**Pull request merged**
