### PR TITLE
Add efmig, GUI for Entity Framework Core migrations

### PR DESCRIPTION
**Pull request by stil**
Project link: https://github.com/stil/efmig

Screenshot:
image

### CODE REVIEW

**Comment by stil** [comment]
Let me know if there's anything missing for this addition to be merged

**Comment by OmidID** [comment]
@stil Thanks for contributing. In terms of UI is very simple. The whole idea of the app is perfect but you need to work much much much more on UI to have an awesome UI. 
Do not panic, Even though I have some projects which are not awesome yet and have not added here :) 
We try to clean the awesome list and not add anything.

I would like to give you some idea:
1. Add more UI elements instead of print text. such as a list of migrations.
2. Add multi-database engine support which is so complicated to do by command line. 
3. Database actions such as (update, create, ....)
4. Maybe it would be a good idea to split the main window with 2 columns at the top (Migrations list on the left, Migration details on the right) and logs on the bottom.
5. It would be great if the user can run it from VSCode directly

**Comment by stil** [comment]
Thanks for feedback. I'll reopen the PR once it's ready.

**Comment by OmidID** [comment]
Thanks for understanding.

**Pull request closed without merging**
