### PR TITLE
added  EremexControls

### PR DESCRIPTION
**Pull request by RomanKalachik**

### CODE REVIEW

**Comment by OmidID** [comment]
Hello @RomanKalachik 
I do not see any source code!

**Comment by RomanKalachik** [comment]
> Hello @RomanKalachik I do not see any source code!

Controls source code is available for customers only.

> Hello @RomanKalachik I do not see any source code!

It is a closed source commercial product made with Avalonia. Demo application source code is available at 
https://github.com/Eremex/controls-demo/

**Comment by OmidID** [comment]
@RomanKalachik  OK. Please change the text to `Commercial Powerful UI controls for the cross-platform Avalonia UI framework to help you deliver cutting-edge applications with enhanced UX.`

**Comment by RomanKalachik** [comment]
> @RomanKalachik OK. Please change the text to `Commercial Powerful UI controls for the cross-platform Avalonia UI framework to help you deliver cutting-edge applications with enhanced UX.`
> 
> And also resolve the confilict.
> 
> Thanks

@OmidID sure, corrected description as suggested

**Pull request merged**
